name: ssu-ai
channels:
  - conda-forge
  - defaults
  - https://conda.anaconda.org/conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - aiohappyeyeballs=2.4.6=pyhd8ed1ab_0
  - aiohttp=3.11.12=py310h89163eb_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - alsa-lib=1.2.13=hb9d3cd8_0
  - anyio=4.8.0=pyhd8ed1ab_0
  - aom=3.9.1=hac33072_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py310ha75aee5_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.4=pyhd8ed1ab_1
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attr=2.5.1=h166bdaf_1
  - attrs=25.1.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.3=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blosc=1.21.6=he440d0b_1
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py310hf71b8c6_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.1.31=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.5.1=pyhd8ed1ab_0
  - cairo=1.18.2=h3394656_1
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py310h8deb56e_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.1=py310h3788b33_0
  - cryptography=44.0.1=py310h6c63255_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.12=py310hf71b8c6_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=h5888daf_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.6.4=h5888daf_0
  - ffmpeg=7.1.0=gpl_h38e10fd_712
  - fftw=3.3.10=nompi_hf1063bd_110
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.56.0=py310h89163eb_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.12.1=h267a509_2
  - freexl=2.0.0=h9dce30a_2
  - fribidi=1.0.10=h516909a_0
  - frozenlist=1.5.0=py310h89163eb_1
  - gdal=3.10.2=py310h79127d3_0
  - gdk-pixbuf=2.42.12=hb9ae30d_0
  - geos=3.13.0=h5888daf_0
  - geotiff=1.7.3=h77b800c_3
  - gettext=0.23.1=h5888daf_0
  - gettext-tools=0.23.1=h5888daf_0
  - giflib=5.2.2=hd590300_0
  - glib=2.82.2=h07242d1_1
  - glib-networking=2.80.0=h2ef3c98_0
  - glib-tools=2.82.2=h4833e2c_1
  - gmp=6.3.0=hac33072_2
  - gnutls=3.8.9=h5746830_0
  - google-api-core=2.24.1=pyhd8ed1ab_0
  - google-api-python-client=2.161.0=pyhff2d567_0
  - google-auth=2.38.0=pyhd8ed1ab_0
  - google-auth-httplib2=0.2.0=pyhd8ed1ab_1
  - google-colab=1.0.0=pyh44b312d_0
  - googleapis-common-protos=1.67.0=pyhd8ed1ab_0
  - graphite2=1.3.13=h59595ed_1003
  - gsl=2.7=he838d99_0
  - gst-plugins-base=1.24.7=h0a52356_0
  - gst-plugins-good=1.24.7=h86e0682_0
  - gstreamer=1.24.7=hf3bb09a_0
  - h11=0.14.0=pyhd8ed1ab_1
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=10.2.0=h4bba637_0
  - hdf5=1.14.3=nompi_h2d575fe_109
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.7=pyh29332c3_1
  - httplib2=0.22.0=pyhd8ed1ab_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - ihm=2.2=py310ha75aee5_0
  - imath=3.1.12=h7955e40_0
  - imp=2.22.0=py310hed9ead8_3
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_metadata=8.6.1=hd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.32.0=pyh907856f_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jack=1.9.22=h7c63dc7_2
  - jasper=4.2.4=h536e39c_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.5=pyhd8ed1ab_0
  - json-c=0.18=h6688a6e_0
  - json5=0.10.0=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py310hff52083_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.15.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.3.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py310h3788b33_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - level-zero=1.20.5=h84d6215_0
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libaec=1.1.3=h59595ed_0
  - libarchive=3.7.7=h4585015_3
  - libasprintf=0.23.1=h8e693c7_0
  - libasprintf-devel=0.23.1=h8e693c7_0
  - libass=0.17.3=hba53ac1_1
  - libavif16=1.1.1=h1909e37_2
  - libblas=3.9.0=29_h59b9bed_openblas
  - libboost=1.86.0=h6c02f8c_3
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcap=2.71=h39aace5_0
  - libcblas=3.9.0=29_he106b2a_openblas
  - libclang-cpp18.1=18.1.8=default_hb5137d0_7
  - libclang-cpp19.1=19.1.7=default_hb5137d0_1
  - libclang13=19.1.7=default_h9c6a7e4_1
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.12.1=h332b0f4_0
  - libdb=6.2.32=he1b5a44_0
  - libde265=1.0.15=h00ab1b0_0
  - libdeflate=1.23=h4ddbbb0_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libfabric=2.0.0=ha770c72_1
  - libfabric1=2.0.0=h14e6f36_1
  - libffi=3.4.6=h2dba641_0
  - libflac=1.4.3=h59595ed_0
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgcrypt=1.11.0=ha770c72_2
  - libgcrypt-devel=1.11.0=hb9d3cd8_2
  - libgcrypt-lib=1.11.0=hb9d3cd8_2
  - libgcrypt-tools=1.11.0=hb9d3cd8_2
  - libgdal-core=3.10.2=h3359108_0
  - libgettextpo=0.23.1=h5888daf_0
  - libgettextpo-devel=0.23.1=h5888daf_0
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.82.2=h2ff4ddf_1
  - libglu=9.0.3=h03adeef_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h77fa898_1
  - libgpg-error=1.51=hbd13f7d_1
  - libheif=1.19.5=gpl_hc21c24c_100
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - libkml=1.3.0=hf539b9f_1021
  - liblapack=3.9.0=29_h7ac8fdf_openblas
  - liblapacke=3.9.0=29_he2f377e_openblas
  - libllvm18=18.1.8=ha7bfdaf_3
  - libllvm19=19.1.7=ha7bfdaf_1
  - liblzma=5.6.4=hb9d3cd8_0
  - liblzma-devel=5.6.4=hb9d3cd8_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=h4ab18f5_0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libopencv=4.11.0=qt6_py310hd7acd64_602
  - libopenvino=2025.0.0=hdc3f47d_1
  - libopenvino-auto-batch-plugin=2025.0.0=h4d9b6c2_1
  - libopenvino-auto-plugin=2025.0.0=h4d9b6c2_1
  - libopenvino-hetero-plugin=2025.0.0=h981d57b_1
  - libopenvino-intel-cpu-plugin=2025.0.0=hdc3f47d_1
  - libopenvino-intel-gpu-plugin=2025.0.0=hdc3f47d_1
  - libopenvino-intel-npu-plugin=2025.0.0=hdc3f47d_1
  - libopenvino-ir-frontend=2025.0.0=h981d57b_1
  - libopenvino-onnx-frontend=2025.0.0=h6363af5_1
  - libopenvino-paddle-frontend=2025.0.0=h6363af5_1
  - libopenvino-pytorch-frontend=2025.0.0=h5888daf_1
  - libopenvino-tensorflow-frontend=2025.0.0=h630ec5c_1
  - libopenvino-tensorflow-lite-frontend=2025.0.0=h5888daf_1
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.46=h943b412_0
  - libpq=17.3=h27ae623_0
  - libprotobuf=5.28.3=h6128344_1
  - libpsl=0.21.5=h792ea30_0
  - librsvg=2.58.4=h49af25d_2
  - librttopo=1.1.0=h97f6797_17
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsoup=3.4.4=h5006749_2
  - libspatialite=5.1.0=h1b4f908_12
  - libsqlite=3.48.0=hee588c1_1
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libsystemd0=257.3=h3dc2cb9_0
  - libtasn1=4.20.0=hb9d3cd8_0
  - libudev1=257.3=h9a4d06a_0
  - libunistring=0.9.10=h14c3975_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h8a09558_1
  - libvorbis=1.3.7=he1b5a44_0
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.8.0=hc4a0caf_0
  - libxml2=2.13.5=h8d12d68_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=19.1.7=h024ca30_0
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=hd590300_1001
  - markupsafe=3.0.2=py310h89163eb_1
  - matplotlib-base=3.10.0=py310h68603db_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - minizip=4.0.7=h05a5f5f_3
  - mistune=3.1.1=pyhd8ed1ab_0
  - mkl=2024.2.2=ha957f24_16
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mpi=1.0.1=mpich
  - mpich=4.3.0=h1a8bee6_100
  - msgpack-python=1.1.0=py310h3788b33_0
  - multidict=6.1.0=py310h89163eb_2
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=9.0.1=h266115a_4
  - mysql-libs=9.0.1=he0572af_4
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.9.1=h7ab15ed_0
  - notebook=7.3.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=2.2.3=py310hefbff90_0
  - oauth2client=4.1.3=pyhd8ed1ab_1
  - ocl-icd=2.3.2=hb9d3cd8_2
  - opencl-headers=2024.10.24=h5888daf_0
  - opencv=4.11.0=qt6_py310hcfe8da8_602
  - openexr=3.3.2=h6326327_1
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.9=he970967_0
  - openssl=3.4.1=h7b32b05_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py310h5eaa309_1
  - pandas-stubs=2.2.3.241126=pyhd8ed1ab_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.1=h861ebed_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.44=hba22ea6_2
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py310h7e6dc6c_0
  - pip=25.0.1=pyh8b19718_0
  - pixman=0.44.2=h29eaf8c_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - portpicker=1.6.0=pyhd8ed1ab_2
  - proj=9.5.1=h0054346_0
  - prometheus_client=0.21.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.50=pyha770c72_0
  - propcache=0.2.1=py310h89163eb_1
  - proto-plus=1.26.0=pyhd8ed1ab_0
  - protobuf=5.28.3=py310hf71b8c6_0
  - psutil=6.1.1=py310ha75aee5_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=hb77b528_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-opencv=4.11.0=qt6_py310h5472680_602
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.1=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pydrive=1.3.1=py_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyopenssl=25.0.0=pyhd8ed1ab_0
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.12=hd12c33a_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python_abi=3.10=5_cp310
  - pytz=2024.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pyyaml=6.0.2=py310h89163eb_2
  - pyzmq=26.2.1=py310h71f11fc_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.8.2=h588cce1_0
  - rav1e=0.6.6=he8a937b_2
  - rdma-core=56.0=h5888daf_0
  - readline=8.2=h8228510_1
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rmf=1.7.0=py310h3a8a9ba_1
  - rpds-py=0.22.3=py310h505e2c1_0
  - rsa=4.9=pyhd8ed1ab_1
  - sdl2=2.30.10=h63c27ac_1
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=75.8.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h8bd8927_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.48.0=h9eae976_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - supervision=0.25.1=pyhc576a83_0
  - svt-av1=2.3.0=h5888daf_0
  - tbb=2021.13.0=hceb3a55_1
  - terminado=0.18.1=pyh0d859eb_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.4.2=py310ha75aee5_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20241206=pyhd8ed1ab_0
  - types-pytz=2025.1.0.20250204=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025a=h78e105d_0
  - ucx=1.18.0=hfd9a62f_1
  - unicodedata2=16.0.0=py310ha75aee5_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - uriparser=0.9.8=hac33072_0
  - uritemplate=4.1.1=pyhd8ed1ab_1
  - urllib3=2.3.0=pyhd8ed1ab_0
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.40=hd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xerces-c=3.2.5=h988505b_2
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xorg-damageproto=1.2.1=hb9d3cd8_1003
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.11=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-util-macros=1.20.2=hb9d3cd8_0
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.6.4=hbcc6ac9_0
  - xz-gpl-tools=5.6.4=hbcc6ac9_0
  - xz-tools=5.6.4=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.18.3=py310h89163eb_1
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py310ha39cb0e_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - affine==2.4.0
      - annotated-types==0.7.0
      - backports-tarfile==1.2.0
      - build==1.2.2
      - click-plugins==1.1.1
      - cligj==0.7.2
      - cython==3.0.11
      - dacite==1.8.1
      - docutils==0.21.2
      - geopandas==1.0.1
      - globox==2.4.6
      - htmlmin==0.1.12
      - imagehash==4.3.1
      - imageio==2.35.1
      - ipywidgets==8.1.3
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.0.2
      - jeepney==0.8.0
      - joblib==1.4.2
      - jupyterlab-widgets==3.0.11
      - keyring==25.3.0
      - lazy-loader==0.4
      - libtiff==0.4.2
      - llvmlite==0.43.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - more-itertools==10.5.0
      - multimethod==1.12
      - nh3==0.2.18
      - numba==0.60.0
      - pandas-profiling==3.6.6
      - patsy==0.5.6
      - phik==0.12.4
      - pkginfo==1.10.0
      - pycocotools==2.0.8
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pyogrio==0.9.0
      - pyproj==3.6.1
      - pyproject-hooks==1.1.0
      - pywavelets==1.7.0
      - rasterio==1.3.10
      - readme-renderer==44.0
      - requests-toolbelt==1.0.0
      - rfc3986==2.0.0
      - rich==13.8.0
      - rioxarray==0.17.0
      - scikit-image==0.24.0
      - scipy==1.13.1
      - secretstorage==3.3.3
      - shapely==2.0.6
      - snuggs==1.4.7
      - statsmodels==0.14.2
      - tifffile==2024.8.30
      - twine==5.1.1
      - typeguard==4.3.0
      - ultralytics==8.3.51
      - ultralytics-yolo==0.0.1
      - visions==0.7.6
      - widgetsnbextension==4.0.11
      - wordcloud==1.9.3
      - xarray==2024.7.0
      - ydata-profiling==4.9.0
